#' Plot Summary of Missing Data Across Assays
#'
#' Visualizes the number of features exceeding a missing data threshold in each assay of a `MultiAssayExperiment` object.
#'
#' @param expomicset A `MultiAssayExperiment` object with missing data summary stored in `metadata(expomicset)$na_qc`.
#' @param threshold A numeric value specifying the missing data percentage threshold for features to be counted. Default is `20`.
#'
#' @details
#' This function extracts missing data summaries from `metadata(expomicset)$na_qc`, generated by `filter_missing()`,
#' and counts the number of features in each assay exceeding the specified missingness threshold. The results are:
#'
#' - Displayed as a **bar plot**, where bars represent different assays.
#' - Labeled with the number of features exceeding the threshold.
#' - Colored by assay name for easy distinction.
#'
#' @return A `ggplot` object showing missing data statistics across assays.
#'
#' @examples
#' \dontrun{
#' plot_missing_summary(expom, threshold = 10)
#' }
#'
#' @export
plot_missing_summary <- function(
    expomicset,
    threshold=20){
  require(ggplot2)

  # check if the required metadata is present
  if(!"na_qc" %in% names(MultiAssayExperiment::metadata(expomicset))){
    stop("Please run `filter_missing()` first.")
  }

  # Plot missing data summary
  qc_res <- MultiAssayExperiment::metadata(expomicset)$na_qc

  # loop through each omic and determine which layers have missing data
  missing_data <- purrr::imap(MultiAssayExperiment::metadata(expomicset)$na_qc, ~ {

    df <- .x$all_var_sum |>
      dplyr::filter(pct_miss>threshold)

    # Ensure df is a data frame
    if (is.null(df)) {
      return(NULL)
    }

    if (nrow(df) > 0) {
      df <- df |>
        dplyr::mutate(exp_name = .y)
    }

    return(df)  # Always return df, even if empty
  }) |>
    dplyr::bind_rows() |>
    dplyr::group_by(exp_name) |>
    dplyr::summarise(missingness = dplyr::n())

  # add in other assay names and say their missingness is 0
  exp_names <- MultiAssayExperiment::metadata(expomicset)$na_qc |>
    names()

  missing_data <- missing_data |>
    dplyr::bind_rows(
      data.frame(
        exp_name = exp_names[!exp_names %in% missing_data$exp_name],
        missingness = 0)) |>
    dplyr::mutate(exp_name=dplyr::case_when(
      exp_name == "exposure" ~ "Exposure",
      .default = exp_name
    )) |>
    dplyr::mutate(exp_name = paste(exp_name, " (", missingness, ")", sep = ""))

  # plot missing data summary
  missing_data |>
    ggplot(aes(y = forcats::fct_reorder(exp_name, missingness),
               x = missingness,
               fill = exp_name)) +
    geom_bar(stat = "identity",alpha=0.7) +
    geom_segment(aes(
      x = missingness,
      xend = missingness,
      y = as.numeric(forcats::fct_reorder(exp_name, missingness)) - 0.45,
      yend = as.numeric(forcats::fct_reorder(exp_name, missingness)) + 0.45,
      color = exp_name,
    ), size = 1) +
    scale_fill_tidy_exp()+
    scale_color_tidy_exp()+
    labs(title = paste("No. of Features Over ", threshold, "%"," Threshold",sep=""),
         y = "",
         x = "No. of Features") +
    ggpubr::theme_pubr(legend="none")

}
