#' Identify and Annotate Shared Top Features Across Integration Factors
#'
#' Identifies top features that are shared (overlapping) across all integration factors (e.g., MOFA or MCIA),
#' and optionally annotates whether these features are also robustly associated with the outcome (e.g., DEGs or stability-selected).
#'
#' @param expomicset A `MultiAssayExperiment` containing `top_factor_features` in its metadata (usually generated by `extract_top_factor_features()`).
#' @param robust_comparison Logical; if `TRUE`, uses sensitivity analysis (if available) to define robust associations. If `FALSE`, uses traditional DEG filters. Default is `TRUE`.
#' @param stability_score Optional numeric threshold for robust filtering. If `NULL`, uses the `score_thresh` stored in `metadata(expomicset)$sensitivity_analysis`.
#' @param score_col Character string specifying which score column to use from sensitivity analysis. Default is `"stability_score"`.
#' @param pval_thresh P-value threshold for differential abundance filtering. Used if `robust_comparison = FALSE`. Default is `0.05`.
#' @param logfc_thresh Log fold change threshold for differential abundance filtering. Used if `robust_comparison = FALSE`. Default is `log2(1.5)`.
#' @param pval_col Character string specifying the column in the differential abundance table containing p-values. Default is `"padj"`.
#' @param logfc_col Character string specifying the column in the differential abundance table containing log fold changes. Default is `"logFC"`.
#' @param action What to do with the results:
#' \describe{
#'   \item{"add"}{Store shared top features in `metadata(expomicset)$common_top_factor_features` and return the updated object.}
#'   \item{"get"}{Return the data frame of shared top features across all factors, including an `is_deg` column indicating outcome association.}
#' }
#'
#' @return Either a modified `MultiAssayExperiment` object (if `action = "add"`), or a `data.frame` of overlapping top features (if `action = "get"`).
#' @export
run_factor_overlap <- function(
    expomicset,
    robust_comparison = TRUE,
    stability_score = NULL,
    score_col = "stability_score",
    pval_thresh = 0.05,
    logfc_thresh = log2(1.5),
    pval_col = "padj",
    logfc_col = "logFC",
    action = "add") {

  # Check if the required data is available
  if(!("top_factor_features" %in% names(MultiAssayExperiment::metadata(expomicset)$multiomics_integration))){
    stop("Please run 'extract_top_factor_features()' first.")
  }

  # Extract the top factor features
  top_factor_features <- expomicset |>
    MultiAssayExperiment::metadata() |>
    purrr::pluck("multiomics_integration") |>
    purrr::pluck("top_factor_features") |>
    dplyr::mutate(exp_name_feature = paste(exp_name, feature, sep = "_"))

  # Identify common features across all factors
  common_features <- top_factor_features |>
    (\(df) split(df, df$factor))() |>
    purrr::map(~{
      .x |>
        dplyr::select(exp_name_feature) |>
        dplyr::distinct() |>
        dplyr::pull(exp_name_feature)
    }) |>
    (\(lst) Reduce(intersect, lst))()

  # Filter the original top factor features by common features
  top_factor_features <- top_factor_features |>
    dplyr::filter(exp_name_feature %in% common_features) |>
    dplyr::select(-exp_name_feature)

  # Identify robust features
  if (robust_comparison) {
    # Use default threshold if not provided
    if (is.null(stability_score)) {
      score <- expomicset |>
        MultiAssayExperiment::metadata() |>
        purrr::pluck("differential_analysis") |>
        purrr::pluck("sensitivity_analysis") |>
        purrr::pluck("score_thresh")
    } else {
      score <- stability_score
    }

    # Filter based on selected score column
    da_res <- expomicset |>
      MultiAssayExperiment::metadata() |>
      purrr::pluck("differential_analysis") |>
      purrr::pluck("sensitivity_analysis") |>
      purrr::pluck("feature_stability") |>
      dplyr::filter(!!rlang::sym(score_col) > score) |>
      dplyr::select(exp_name, feature) |>
      dplyr::distinct() |>
      dplyr::mutate(exp_name_feature = paste0(exp_name, "_", feature))

  } else {
    # Use DEG thresholds
    da_res <- expomicset |>
      MultiAssayExperiment::metadata() |>
      purrr::pluck("differential_analysis") |>
      purrr::pluck("differential_abundance") |>
      dplyr::filter(
        !!rlang::sym(pval_col) < pval_thresh,
        abs(!!rlang::sym(logfc_col)) > logfc_thresh
      ) |>
      dplyr::select(exp_name, feature) |>
      dplyr::distinct() |>
      dplyr::mutate(exp_name_feature = paste0(exp_name, "_", feature))
  }

  # Annotate overlap table with DEG/robust flag
  top_factor_features <- top_factor_features |>
    dplyr::mutate(exp_name_feature = paste0(exp_name, "_", feature)) |>
    dplyr::mutate(is_deg = exp_name_feature %in% da_res$exp_name_feature)

  message(paste0("Found ", length(common_features), " common features across factors."))

  if (action == "add") {
    # Store results in metadata
    MultiAssayExperiment::metadata(expomicset)$multiomics_integration$common_top_factor_features <- top_factor_features

    # Record analysis step
    step_record <- list(
      run_factor_overlap = list(
        timestamp = Sys.time(),
        params = list(
          robust_comparison = robust_comparison,
          stability_score = stability_score,
          score_col = score_col,
          pval_thresh = pval_thresh,
          logfc_thresh = logfc_thresh
        ),
        notes = paste0(
          "Identified shared top features across integration factors and ",
          if (robust_comparison) {
            paste0("annotated based on '", score_col, "' scores.")
          } else {
            "annotated based on differential abundance thresholds."
          }
        )
      )
    )

    MultiAssayExperiment::metadata(expomicset)$summary$steps <- c(
      MultiAssayExperiment::metadata(expomicset)$summary$steps,
      step_record
    )

    return(expomicset)

  } else if (action == "get") {
    return(top_factor_features)

  } else {
    stop("Invalid action. Choose 'add' or 'get'.")
  }
}
