#' Identify and Annotate Shared Top Features Across Integration Factors
#'
#' Identifies top features that are shared (overlapping) across all integration factors (e.g., MOFA or MCIA),
#' and optionally annotates whether these features are also robustly associated with the outcome (e.g., DEGs or stability-selected).
#'
#' @param expomicset A `MultiAssayExperiment` containing `top_factor_features` in its metadata (usually generated by `extract_top_factor_features()`).
#' @param robust_comparison Logical; if `TRUE`, uses sensitivity analysis (if available) to define robust associations. If `FALSE`, uses traditional DEG filters. Default is `TRUE`.
#' @param stability_score Optional numeric threshold for robust filtering. If `NULL`, uses the `score_thresh` stored in `metadata(expomicset)$sensitivity_analysis`.
#' @param pval_thresh P-value threshold for differential abundance filtering. Used if `robust_comparison = FALSE`. Default is `0.05`.
#' @param logfc_thresh Log fold change threshold for differential abundance filtering. Used if `robust_comparison = FALSE`. Default is `log2(1.5)`.
#' @param pval_col Character string specifying the column in the differential abundance table containing p-values. Default is `"padj"`.
#' @param logfc_col Character string specifying the column in the differential abundance table containing log fold changes. Default is `"logFC"`.
#' @param action What to do with the results:
#' \describe{
#'   \item{"add"}{Store shared top features in `metadata(expomicset)$common_top_factor_features` and return the updated object.}
#'   \item{"get"}{Return the data frame of shared top features across all factors, including an `is_deg` column indicating outcome association.}
#' }
#'
#' @details
#' This function:
#' \itemize{
#'   \item Identifies overlapping top features across all integration factors using the `exp_name_feature` identifier.
#'   \item Optionally evaluates whether shared features are robustly associated with an outcome using:
#'     \itemize{
#'       \item Sensitivity analysis scores (if `robust_comparison = TRUE`).
#'       \item P-value and logFC thresholds (if `robust_comparison = FALSE`).
#'     }
#'   \item Adds a boolean `is_deg` column to annotate features that meet DEG or stability criteria.
#' }
#'
#' @return Either a modified `MultiAssayExperiment` object (if `action = "add"`), or a `data.frame` of overlapping top features (if `action = "get"`).
#'
#' @examples
#' \dontrun{
#' # Add shared top features to metadata
#' expomicset <- run_factor_overlap(expomicset, action = "add")
#'
#' # Get the table of shared features directly
#' shared_df <- run_factor_overlap(expomicset, action = "get")
#' }
#'
#' @export
run_factor_overlap <- function(
    expomicset,
    robust_comparison = TRUE,
    stability_score = NULL,
    pval_thresh = 0.05,
    logfc_thresh = log2(1.5),
    pval_col = "padj",
    logfc_col = "logFC",
    action = "add"){

  # Check if the required data is available
  if(!("top_factor_features" %in% names(MultiAssayExperiment::metadata(expomicset)))){
    stop("Please run 'extract_top_factor_features()' first.")
  }

  # Extract the top factor features
  top_factor_features <- expomicset |>
    MultiAssayExperiment::metadata() |>
    pluck("top_factor_features") |>
    mutate(exp_name_feature=paste(
      exp_name, feature, sep="_"
    ))

  # Check for overlapping features across factors
  common_features <- top_factor_features |>
    # make a list by factor and look for overlaps in exp_name_feature
    (\(df)split(df,df$factor))() |>
    purrr::map(~{
      .x |>
        dplyr::select(exp_name_feature) |>
        dplyr::distinct() |>
        dplyr::pull(exp_name_feature)
    }) |>
    (\(lst) Reduce(intersect,lst))()

  # Filter the original top factor features by common features
  top_factor_features <- top_factor_features |>
    dplyr::filter(exp_name_feature %in% common_features) |>
    dplyr::select(-exp_name_feature)

  if(robust_comparison){
    # Check if sensitivity analysis metadata is available
    if (is.null(stability_score)) {
      score <- expomicset |>
        MultiAssayExperiment::metadata() |>
        pluck("sensitivity_analysis") |>
        pluck("score_thresh")
    } else {
      score <- stability_score
    }

    # Filter based on stability score
    da_res <- expomicset |>
      MultiAssayExperiment::metadata() |>
      pluck("sensitivity_analysis") |>
      pluck("feature_stability") |>
      dplyr::filter(
        stability_score>score) |>
      dplyr::select(exp_name,feature) |>
      distinct()|>
      mutate(exp_name_feature = paste0(exp_name, "_", feature))

  } else{
    # Filter based on p-value and log fold change thresholds
    da_res <- expomicset |>
      MultiAssayExperiment::metadata() |>
      pluck("differential_abundance") |>
      dplyr::filter(
        !!sym(pval_col) < pval_thresh,
        abs(!!sym(logfc_col)) > logfc_thresh) |>
      dplyr::select(exp_name, feature) |>
      distinct() |>
      mutate(exp_name_feature = paste0(exp_name, "_", feature))
  }

  # Create a data frame where the we see if the top factor features are degs
  top_factor_features <- top_factor_features |>
    mutate(exp_name_feature = paste0(exp_name, "_", feature)) |>
    mutate(is_deg = exp_name_feature %in% da_res$exp_name_feature)

  message(paste0("Found ", length(common_features), " common features across factors."))

  if(action=="add"){
    # Store selected features
    MultiAssayExperiment::metadata(expomicset)$common_top_factor_features <- top_factor_features

    # Add analysis steps taken to metadata
    MultiAssayExperiment::metadata(expomicset)$steps <- c(
      MultiAssayExperiment::metadata(expomicset)$steps,
      "run_factor_overlap"
    )
    return(expomicset)
  }else if (action=="get"){
    return(top_factor_features)
  }else{
    stop("Invalid action. Choose 'add' or 'get'.")
  }


}
